version: 2
vm_settings: &vm_settings
  docker:
    - image: circleci/node:6.12.3-browsers

jobs:
  install_template_deps:
    <<: *vm_settings
    working_directory: ~/project/webpack-template
    steps:
      - checkout
      - restore_cache:
          key: template-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: template-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Rollout full-karma-airbnb scenario
          command: VUE_TEMPL_TEST=full-karma-airbnb node_modules/.bin/vue init . test-full-karma-airbnb
      - persist_to_workspace:
          root: ~/project/webpack-template
          paths:
            - node_modules
            - test-*

  scenario_full-karma-airbnb:
    <<: *vm_settings
    working_directory: ~/project/webpack-template/test-full-karma-airbnb
    environment:
      - VUE_TEMPL_TEST: full-karma-airbnb
    steps:
      - attach_workspace:
          at: '~/project/webpack-template'
      - restore_cache:
          key: template-cache-full-karma-airbnb-{{ checksum "package.json" }}
      - run:
          name: Update chrome to latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: template-cache-full-karma-airbnb-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Lint
          command: npm run lint -- --fix
      - run:
          name: Run Unit tests
          command: npm run unit
          when: always
      - run:
          name: Run e2e tests
          command: npm run e2e
          when: always
      - run:
          name: Test build
          command: npm run build
          when: always


workflows:
  version: 2
  build_and_test:
    jobs:
      - install_template_deps
      - scenario_full-karma-airbnb:
          requires:
            - install_template_deps
